const PREFIX = 'TODO/'

export const ADD_TODO = PREFIX + 'ADD_TODO'
export const COMPLETE_TODO = PREFIX + 'COMPLETE_TODO'
export const UPDATE_TODO = PREFIX + 'UPDATE_TODO'
export const REMOVE_TODO = PREFIX + 'REMOVE_TODO'
export const SET_STATUS_FILTER = PREFIX + 'SET_STATUS_FILTER'
export const SET_PRIORITY_FILTER = PREFIX + 'SET_PRIORITY_FILTER'
