const PREFIX = 'TODO_FILTER/'

export const STATUS_ALL = PREFIX + 'STATUS_ALL'
export const STATUS_COMPLETED = PREFIX + 'STATUS_COMPLETED'
export const STATUS_ACTIVE = PREFIX + 'STATUS_ACTIVE'

export const PRIORITY_ALL = PREFIX + 'PRIORITY_ALL'
export const PRIORITY_HIGH = PREFIX + 'PRIORITY_HIGH'
export const PRIORITY_MEDIUM = PREFIX + 'PRIORITY_MEDIUM'
export const PRIORITY_LOW = PREFIX + 'PRIORITY_LOW'
export const PRIORITY_NONE = PREFIX + 'PRIORITY_NONE'
